// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace appointment_module_api.Models
{
    public partial class Appointments
    {
        public long ApptId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public int ServiceId { get; set; }
        public int Confirmed { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public DateTime ApptDate { get; set; }
        public int? LengthMinutes { get; set; }
        public int? BusinessId { get; set; }
    }
}