// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace appointment_module_api.Models
{
    public partial class Business
    {
        public long BusinessId { get; set; }
        public string BusinessName { get; set; }
        public string Icon { get; set; }
        public string Admin { get; set; }
    }
}