// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace appointment_module_api.Models
{
    public partial class BusinessHours
    {
        public long BusinessHourId { get; set; }
        public string Day { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public int BusinessId { get; set; }
        public int? QuarterInt { get; set; }
        public int? HalfInt { get; set; }
        public int? FullInt { get; set; }
    }
}