// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace appointment_module_api.Models
{
    public partial class get_business_for_adminResult
    {
        public long business_id { get; set; }
        public string business_name { get; set; }
        public string confirmedAppts { get; set; }
    }
}
