// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace appointment_module_api.Models
{
    public partial class get_times_for_serviceResult
    {
        public int length { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public int? totalHours { get; set; }
        public int? interval { get; set; }
        public string takenAppts { get; set; }
    }
}
