// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace appointment_module_api.Models
{
    public partial class selecting_business_servicesResult
    {
        public string service_category { get; set; }
        public string serviceNames { get; set; }
    }
}
