// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace appointment_module_api.Models
{
    public partial class Services
    {
        public long ServiceId { get; set; }
        public string ServiceName { get; set; }
        public int BusinessId { get; set; }
        public int LengthMinutes { get; set; }
        public string ServiceCategory { get; set; }
    }
}